# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Yi Li 李毅
title: 
email: liyigerry@163.com
website: https://liyigerry.github.io

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Researcher and Teacher in Dali University
  Foucus on biological intelligent computing and engineering
  Welcome to visit our lab
  欢迎关注：玉局峰讲习社

# Projects Section
# projects_title: Projects

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
