# Site
repository: liyigerry/liyigerry.github.io
favicon: images/favicon.ico

# Personal info
name: 李毅 Yi Li
title: Ph.D. 
email: liyigerry@163.com
website: https://liyigerry.github.io

# About Section
about_title: 基本信息 About Me
about_profile_image: images/profile.jpg
about_content: |
  在 大理大学 任教、开展研究

  Researcher and Teacher in Dali University

  关注生物智能计算和工程

  Foucus on biological intelligent computing and engineering

  欢迎关注：玉局峰讲习社

  Welcome to visit our lab

# Projects Section
projects_title: 项目 Projects

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
