# Site
repository: liyigerry/liyigerry.github.io
favicon: images/favicon.ico

# Personal info
name: 李毅 Yi Li
title: Ph.D. 
email: liyigerry@163.com
website: https://liyigerry.github.io

# About Section
about_title: 基本信息 About Me
about_profile_image: images/profile.jpg
about_content: |
  在 <mark>大理大学</mark> 任教 《机器学习》 《人工智能导论》

  Researcher and Teacher in Dali University

  关注生物智能计算和工程

  Focus on biological intelligent computing and engineering

  招收 <mark>硕士研究生</mark> 方向

  1.机器学习在生物学的应用

  2.生物实验相关的电子设计

  欢迎关注微信公众号：玉局峰讲习社

  Welcome to visit our lab

# Projects Section
projects_title: 项目 Projects

# Experience Section
experience_title: 文章 Publish

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
